stages:
  - build
  - test

build:
  stage: build
  script: npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/
  only:
    - merge_requests

test:unit:
  stage: test
  script:
    - npm run test
  dependencies:
    - build
  only:
    - merge_requests
