image: node:latest

stages:
  - build
  - test

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build:
  stage: build
  script: npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/
  only:
    - merge_requests

test:unit:
  stage: test
  script:
    - npm run test
  dependencies:
    - build
  only:
    - merge_requests
