image: node:latest

stages:
  - build
  - test
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build:
  stage: build
  script: npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/
  only:
    - merge_requests

test:unit:
  stage: test
  script:
    - npm run test
  dependencies:
    - build
  only:
    - merge_requests

production:
  image: python:3.8
  stage: deploy
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - sam build
    - sam package --output-template-file packaged.yaml --s3-bucket $SAM_S3_BUCKET
    - sam deploy --template-file packaged.yaml --stack-name livelot-sam --s3-bucket $SAM_S3_BUCKET --s3-prefix $SAM_S3_PREFIX --capabilities CAPABILITY_IAM --region us-east-2
  only:
    - master
  # environment: production
