image: node:latest

stages:
  - build
  - test
  - deploy-stage
  - deploy-master
# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build:
  stage: build
  script: npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/
  only:
    - merge_requests

test:unit:
  stage: test
  script:
    - npm run test
  dependencies:
    - build
  only:
    - merge_requests

deploy:stage:
  image: nikolaik/python-nodejs
  stage: deploy-stage
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - npm run build
    - sam build --parameter-overrides "StageType=stage" "BranchName=master"
    - sam package --output-template-file packaged.yaml --s3-bucket $SAM_S3_BUCKET --s3-prefix $SAM_S3_PREFIX --region us-east-2
    - sam deploy --template-file packaged.yaml --stack-name livelot-sam-stage --s3-bucket $SAM_S3_BUCKET --s3-prefix $SAM_S3_PREFIX --capabilities CAPABILITY_IAM --region us-east-2 --no-confirm-changeset --parameter-overrides "StageType=stage" "BranchName=master"
  only:
    - master

deploy:production:
  image: nikolaik/python-nodejs
  stage: deploy-master
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - npm run build
    - sam build --parameter-overrides "StageType=prod" "BranchName=master"
    - sam package --output-template-file packaged.yaml --s3-bucket $SAM_S3_BUCKET --s3-prefix $SAM_S3_PREFIX --region us-east-2
    - sam deploy --template-file packaged.yaml --stack-name livelot-sam-prod --s3-bucket $SAM_S3_BUCKET --s3-prefix $SAM_S3_PREFIX --capabilities CAPABILITY_IAM --region us-east-2 --no-confirm-changeset --parameter-overrides "StageType=prod" "BranchName=master"
  dependencies:
    - deploy-stage
  only:
    - master
  when: manual
